import type { DemoScenarioStep } from "../engine/types";

export const quoteFlowScenario: DemoScenarioStep[] = [
  {
    id: "tap-new-quote",
    screen: "dashboard",
    action: "tapFab",
    durationMs: 1700,
    caption: "Tap the center plus",
    voiceover: "The provider starts a quote from the same action available across the app.",
    events: [
      {
        id: "tap-fab",
        type: "tap",
        target: "fab",
        atMs: 620,
        durationMs: 520,
        caption: "Tap +",
        voiceover: "Start from the same plus button on every main screen.",
      },
    ],
  },
  {
    id: "type-customer",
    screen: "customer",
    action: "typeCustomer",
    durationMs: 2600,
    caption: "Customer and job details, quickly",
    voiceover: "Basic customer and job details create the quote shell before any pricing happens.",
    events: [
      {
        id: "type-customer-name",
        type: "type",
        target: "customerName",
        value: "Michael",
        atMs: 300,
        durationMs: 600,
        caption: "Enter customer",
        voiceover: "First, capture who the quote is for.",
      },
      {
        id: "type-job-address",
        type: "type",
        target: "jobAddress",
        value: "18 Victor Ave",
        atMs: 1000,
        durationMs: 750,
        caption: "Add job address",
        voiceover: "The address anchors the job record and quote link.",
      },
      {
        id: "type-job-title",
        type: "type",
        target: "jobTitle",
        value: "Interior repaint",
        atMs: 1750,
        durationMs: 600,
        caption: "Name the job",
        voiceover: "A short job title makes the quote easier to recognize later.",
      },
      {
        id: "tap-customer-next",
        type: "tap",
        target: "nextButton",
        atMs: 2340,
        durationMs: 260,
      },
    ],
  },
  {
    id: "set-checklist",
    screen: "job",
    action: "setChecklist",
    durationMs: 2200,
    caption: "Checklist locks quantities",
    voiceover: "Room count, surfaces, coats, and materials become the source of truth for quantities.",
    events: [
      {
        id: "select-medium-rooms",
        type: "select",
        target: "mediumRooms",
        atMs: 420,
        durationMs: 520,
        caption: "Set room count",
        voiceover: "Quantities are selected before the draft is generated.",
      },
      {
        id: "select-two-coats",
        type: "select",
        target: "coats",
        atMs: 1280,
        durationMs: 520,
        caption: "Lock the coat count",
        voiceover: "Checklist values win if the spoken notes conflict later.",
      },
      {
        id: "tap-job-next",
        type: "tap",
        target: "nextButton",
        atMs: 1950,
        durationMs: 250,
      },
    ],
  },
  {
    id: "record-notes",
    screen: "notes",
    action: "recordNotes",
    durationMs: 2000,
    caption: "Talk through extras",
    voiceover: "The provider can talk through details the checklist did not cover.",
    events: [
      {
        id: "record-voice",
        type: "record",
        target: "mic",
        atMs: 320,
        durationMs: 1350,
        caption: "Record job notes",
        voiceover: "Voice captures extras like patch holes, wallpaper, primer, or materials.",
      },
    ],
  },
  {
    id: "resolve-prices",
    screen: "draftReview",
    action: "resolvePrices",
    durationMs: 2600,
    caption: "Prices snap in green",
    voiceover: "Every dollar comes from the provider price book or a price they enter themselves.",
    events: [
      { id: "resolve-line-1", type: "resolve", target: "line-1", atMs: 260, durationMs: 340 },
      { id: "resolve-line-2", type: "resolve", target: "line-2", atMs: 600, durationMs: 340 },
      { id: "resolve-line-3", type: "resolve", target: "line-3", atMs: 940, durationMs: 340 },
      {
        id: "resolve-line-4",
        type: "resolve",
        target: "line-4",
        atMs: 1280,
        durationMs: 340,
        caption: "All lines priced",
        voiceover: "When every line is trusted, the quote becomes ready to send.",
      },
      {
        id: "tap-preview-send",
        type: "tap",
        target: "previewSend",
        atMs: 2040,
        durationMs: 360,
      },
    ],
  },
  {
    id: "send-preview",
    screen: "preview",
    action: "sendQuote",
    durationMs: 2400,
    caption: "Send the customer quote",
    voiceover: "The customer gets a clean private quote link by email.",
    events: [
      {
        id: "tap-send-quote",
        type: "send",
        target: "sendQuote",
        atMs: 1750,
        durationMs: 420,
        caption: "Send by email",
        voiceover: "The customer receives the quote link without needing an account.",
      },
    ],
  },
  {
    id: "open-email",
    screen: "customerEmail",
    action: "openEmail",
    durationMs: 2200,
    caption: "Quote from Bright Coat Painting arrives",
    voiceover: "Michael's inbox gets a plain email with the quote link -- no app or account required.",
    events: [
      {
        id: "tap-quote-email",
        type: "tap",
        target: "quoteEmail",
        atMs: 1350,
        durationMs: 420,
        caption: "Open the email",
        voiceover: "One tap opens the private quote link in the browser.",
      },
    ],
  },
  {
    id: "view-proposal",
    screen: "publicQuote",
    action: "openProposal",
    durationMs: 3400,
    caption: "Customer reviews and accepts",
    voiceover: "A clean, private proposal -- priced, itemized, and ready to accept.",
    events: [
      {
        id: "tap-accept-quote",
        type: "tap",
        target: "acceptQuote",
        atMs: 2700,
        durationMs: 520,
        caption: "Accept the quote",
        voiceover: "Michael accepts right from the browser.",
      },
    ],
  },
  {
    id: "pay-deposit",
    screen: "payment",
    action: "payDeposit",
    durationMs: 2300,
    caption: "Pay the deposit to lock the schedule",
    voiceover: "A deposit can be collected the same moment the quote is accepted.",
    events: [
      {
        id: "tap-pay-deposit",
        type: "tap",
        target: "payDeposit",
        atMs: 1500,
        durationMs: 420,
        caption: "Pay deposit",
        voiceover: "No account needed -- pay securely from the quote link.",
      },
    ],
  },
  {
    id: "status-update",
    screen: "sent",
    action: "updateStatus",
    durationMs: 4600,
    caption: "The provider sees it instantly",
    voiceover: "Back on the provider's phone, the timeline updates as the customer views, accepts, and pays the deposit.",
    events: [
      { id: "mark-viewed", type: "status", target: "viewedStatus", atMs: 950, durationMs: 180 },
      { id: "mark-accepted", type: "status", target: "acceptStatus", atMs: 2150, durationMs: 180 },
      { id: "mark-paid", type: "status", target: "payStatus", atMs: 3350, durationMs: 180 },
    ],
  },
  {
    id: "quotes-list",
    screen: "quotes",
    action: "openQuotes",
    durationMs: 2200,
    caption: "Back to the quote list",
    voiceover: "The provider can see live quotes, prior revisions, and follow-up status.",
  },
];
