import type { DemoScenarioStep } from "../engine/types";

export const quoteFlowScenario: DemoScenarioStep[] = [
  {
    id: "tap-new-quote",
    screen: "dashboard",
    action: "tapFab",
    durationMs: 1500,
    caption: "Tap the center plus",
    voiceover: "The provider starts from the dashboard, with follow-ups, ready drafts, and active quotes visible first.",
    events: [
      {
        id: "tap-fab",
        type: "tap",
        target: "fab",
        atMs: 620,
        durationMs: 520,
        caption: "Tap +",
        voiceover: "Start from the same plus button on every main screen.",
      },
    ],
  },
  {
    id: "pick-customer",
    screen: "customer",
    action: "typeCustomer",
    durationMs: 2200,
    caption: "Pick an existing customer",
    voiceover: "Customer records stay linked to quotes, while the job label keeps each card distinct.",
    events: [
      {
        id: "select-customer",
        type: "type",
        target: "customerName",
        value: "John Doe",
        atMs: 240,
        durationMs: 420,
        caption: "Select customer",
        voiceover: "The quote links to John Doe instead of copying the name onto the quote.",
      },
      {
        id: "type-job-title",
        type: "type",
        target: "jobTitle",
        value: "Interior repaint",
        atMs: 900,
        durationMs: 430,
        caption: "Name the job",
        voiceover: "The optional title gives the quote card a clear job-first label.",
      },
      {
        id: "tap-customer-next",
        type: "tap",
        target: "nextButton",
        atMs: 1660,
        durationMs: 260,
      },
    ],
  },
  {
    id: "set-checklist",
    screen: "job",
    action: "setChecklist",
    durationMs: 1800,
    caption: "Checklist locks quantities",
    voiceover: "Room count, surfaces, coats, and materials become the source of truth for quantities.",
    events: [
      {
        id: "select-medium-rooms",
        type: "select",
        target: "mediumRooms",
        atMs: 320,
        durationMs: 520,
        caption: "Set room count",
        voiceover: "Quantities are selected before the draft is generated.",
      },
      {
        id: "select-two-coats",
        type: "select",
        target: "coats",
        atMs: 960,
        durationMs: 520,
        caption: "Lock the coat count",
        voiceover: "Checklist values win if the spoken notes conflict later.",
      },
      {
        id: "tap-job-next",
        type: "tap",
        target: "nextButton",
        atMs: 1480,
        durationMs: 250,
      },
    ],
  },
  {
    id: "record-notes",
    screen: "notes",
    action: "recordNotes",
    durationMs: 1700,
    caption: "Talk through extras",
    voiceover: "The provider can talk through details the checklist did not cover.",
    events: [
      {
        id: "record-voice",
        type: "record",
        target: "mic",
        atMs: 260,
        durationMs: 1000,
        caption: "Record job notes",
        voiceover: "Voice captures extras like patch holes, wallpaper, primer, or materials.",
      },
      {
        id: "tap-notes-next",
        type: "tap",
        target: "nextButton",
        atMs: 1320,
        durationMs: 260,
      },
    ],
  },
  {
    id: "review-transcript",
    screen: "transcriptReview",
    action: "reviewTranscript",
    durationMs: 1800,
    caption: "Confirm what the app heard",
    voiceover: "The checklist is locked before drafting, and voice can only add extras.",
    events: [
      {
        id: "tap-generate-draft",
        type: "tap",
        target: "generateDraft",
        atMs: 1260,
        durationMs: 300,
        caption: "Generate draft",
        voiceover: "Once the notes look right, generate the priced draft.",
      },
    ],
  },
  {
    id: "resolve-prices",
    screen: "draftReview",
    action: "resolvePrices",
    durationMs: 2200,
    caption: "Prices snap in green",
    voiceover: "Every dollar comes from the provider price book or a price they enter themselves.",
    events: [
      { id: "resolve-line-1", type: "resolve", target: "line-1", atMs: 160, durationMs: 260 },
      { id: "resolve-line-2", type: "resolve", target: "line-2", atMs: 380, durationMs: 260 },
      { id: "resolve-line-3", type: "resolve", target: "line-3", atMs: 600, durationMs: 260 },
      { id: "resolve-line-4", type: "resolve", target: "line-4", atMs: 820, durationMs: 260 },
      { id: "resolve-line-5", type: "resolve", target: "line-5", atMs: 1040, durationMs: 260 },
      { id: "resolve-line-6", type: "resolve", target: "line-6", atMs: 1260, durationMs: 260 },
      {
        id: "resolve-line-7",
        type: "resolve",
        target: "line-7",
        atMs: 1480,
        durationMs: 260,
        caption: "All lines priced",
        voiceover: "When every line is trusted, the quote becomes ready to send.",
      },
      {
        id: "tap-preview-send",
        type: "tap",
        target: "previewSend",
        atMs: 1860,
        durationMs: 300,
      },
    ],
  },
  {
    id: "send-preview",
    screen: "preview",
    action: "sendQuote",
    durationMs: 3400,
    caption: "Send the customer quote",
    voiceover: "The customer gets a clean private quote link by email.",
    events: [
      {
        id: "tap-send-quote",
        type: "send",
        target: "sendQuote",
        atMs: 2860,
        durationMs: 360,
        caption: "Send by email",
        voiceover: "The customer receives the quote link without needing an account.",
      },
    ],
  },
  {
    id: "quote-sent-detail",
    screen: "sent",
    action: "updateStatus",
    durationMs: 3800,
    caption: "The quote is now sent",
    voiceover: "The provider lands on the sent quote detail with the email send recorded in the timeline.",
    events: [
      {
        id: "tap-back-to-quotes",
        type: "tap",
        target: "backToQuotes",
        atMs: 3360,
        durationMs: 280,
        caption: "Back to quotes",
        voiceover: "Back on the list, the sent quote is visible under the Sent filter.",
      },
    ],
  },
  {
    id: "quotes-sent-tab",
    screen: "quotes",
    action: "openQuotes",
    durationMs: 2200,
    caption: "Sent tab shows the emailed quote",
    voiceover: "The sent tab now contains the quote just emailed to John Doe.",
    events: [
      {
        id: "tap-all-quotes",
        type: "tap",
        target: "allQuotesTab",
        atMs: 1420,
        durationMs: 320,
        caption: "Back to all quotes",
        voiceover: "The provider can return to All and keep working through the rest of the pipeline.",
      },
    ],
  },
  {
    id: "open-email",
    screen: "customerEmail",
    action: "openEmail",
    durationMs: 2200,
    caption: "Quote from Bright Coat Painting arrives",
    voiceover: "Michael's inbox gets a plain email with the quote link -- no app or account required.",
    events: [
      {
        id: "tap-quote-email",
        type: "tap",
        target: "quoteEmail",
        atMs: 1350,
        durationMs: 420,
        caption: "Open the email",
        voiceover: "One tap opens the private quote link in the browser.",
      },
    ],
  },
  {
    id: "view-proposal",
    screen: "publicQuote",
    action: "openProposal",
    durationMs: 3400,
    caption: "Customer reviews and accepts",
    voiceover: "A clean, private proposal -- priced, itemized, and ready to accept.",
    events: [
      {
        id: "tap-accept-quote",
        type: "tap",
        target: "acceptQuote",
        atMs: 2700,
        durationMs: 520,
        caption: "Accept the quote",
        voiceover: "Michael accepts right from the browser.",
      },
    ],
  },
  {
    id: "pay-deposit",
    screen: "payment",
    action: "payDeposit",
    durationMs: 2300,
    caption: "Pay the deposit to lock the schedule",
    voiceover: "A deposit can be collected the same moment the quote is accepted.",
    events: [
      {
        id: "tap-pay-deposit",
        type: "tap",
        target: "payDeposit",
        atMs: 1500,
        durationMs: 420,
        caption: "Pay deposit",
        voiceover: "No account needed -- pay securely from the quote link.",
      },
    ],
  },
  {
    id: "customer-profile",
    screen: "customerProfile",
    action: "openCustomer",
    durationMs: 3200,
    caption: "Customer history is one tap away",
    voiceover: "Customer profiles keep call, email, quote history, resend, copy link, follow-up, and archive actions together.",
  },
];
